[package]
name = "async-task"
version = "2.1.1"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/stjepang/async-task"
homepage = "https://github.com/stjepang/async-task"
documentation = "https://docs.rs/async-task"
description = "Task abstraction for building executors"
keywords = ["futures", "task", "executor", "spawn"]
categories = ["asynchronous", "concurrency", "no-std"]
readme = "README.md"

[target.'cfg(unix)'.dependencies]
libc = "0.2.68"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["processthreadsapi"] }

[dev-dependencies]
crossbeam = "0.7.3"
crossbeam-utils = "0.7.2"
futures = "0.3.4"
lazy_static = "1.4.0"
